name: Perturabo Sync and Build

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Sing-Box
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name | sed 's/^v//')
        ARCH=$(dpkg --print-architecture)
        wget "https://github.com/SagerNet/sing-box/releases/download/v${LATEST_VERSION}/sing-box_${LATEST_VERSION}_linux_${ARCH}.deb"
        sudo dpkg -i "sing-box_${LATEST_VERSION}_linux_${ARCH}.deb"
        rm "sing-box_${LATEST_VERSION}_linux_${ARCH}.deb"

    - name: Run Full Build Pipeline
      run: python build.py

    - name: Check and Commit Changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update proxies, rules and adblock"
          git push
        fi