name: Perturabo Sync and Build

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Sing-Box
      run: |
        sudo bash -c "$(curl -L https://boxex.rocks)"

    - name: Run Collector
      run: python collector.py

    - name: Run Checker
      run: python checker.py

    - name: Run Log Parser
      run: python parse_logs.py
      
    - name: Run RKN Parser
      run: python rkn_parser.py

    - name: Run Build AdBlock
      run: python build.py

    - name: Check and Commit Changes
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update proxies, rules and adblock"
          git push
        fi
